image: node

cache:
  paths:
    - node_modules/

pages:
  before_script:
    - npm install
  script:
    - npm run publish
    - mv out/* public
  after_script:
    - rm -rf out
  artifacts:
    paths:
      - public
  only:
    - master
