stages:
  - build
  - pages

build_image:
  stage: build
  image: docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - main
  tags:
    - NSCICDDOCKER

pages:
  stage: pages
  image:
    name: squidfunk/mkdocs-material:7.3.2
    entrypoint:
      - ''
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  tags:
    - NSCICDDOCKER
