stages:
  - build
  - pages

build_image:
  stage: build
  image: docker:dind
  script:
    - docker login ${CI_REGISTRY} -u gitlab-ci-token -p ${CI_BUILD_TOKEN}
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - main
  tags:
    - ns01

pages:
  stage: pages
  image:
    name: squidfunk/mkdocs-material:7.3.2
    entrypoint:
      - ''
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  tags:
    - ns01
